/**
* Script ver 0.02beta
* Writing by Ruslan Kovalev : skidisaster@gmail.com
* Feb.25 2015
* output format changed for ready to use in FireFox Export plugin
* please install this plugin from https://addons.mozilla.org/en-Us/firefox/addon/password-exporter/
*/



// first part of executing script
out="";
out2="";
var dat=document.getElementsByClassName("password");

for(i=0;i<dat.length;i++){
chrome.send('requestShowPassword', [i]);
};

// second part of executing script
out2+='# Generated by Password Exporter; Export format 1.1; Encrypted: false<br/>';
out2+='"hostname","username","password","formSubmitURL","httpRealm","usernameField","passwordField"<br/>';
for(i=0;i<dat.length;i++){x=dat[i].parentNode;
out+="\n"+x.childNodes[0].innerText+"|"+x.childNodes[1].innerText+"|"+x.childNodes[2].childNodes[0].value;
out2+='<br/>"http://'+x.childNodes[0].innerText+'","'+x.childNodes[1].innerText+'","'+x.childNodes[2].childNodes[0].value+'","http://'+x.childNodes[0].innerText+'","","",""';
};
console.log(out);
document.write(out2);
